[package]
name = "gofer"
version = "0.9.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8"
aes-gcm = "0.10"
anyhow = "1.0"
async-trait = "0.1"
base64 = "0.23"
bollard = "0.18"
bytes = "1.12"
chrono = "0.4"
chrono-humanize = "0.2"
clap = { version = "4.6", features = ["derive", "wrap_help"] }
colored = "3.1"
comfy-table = "8.0"
dashmap = "6.2"
dirs = "7.0"
dropshot = { git = "https://github.com/clintjedwards/dropshot.git", tag = "v0.15.1" }
dropshot_endpoint = { git = "https://github.com/clintjedwards/dropshot.git", tag = "v0.15.1" }
figment = { version = "0.10", features = ["env", "toml"] }
futures = "0.3"
gofer_sdk = { path = "../sdk/rust" }
http = "1.5"
human-panic = "2.0"
hyper = { version = "1.11", features = ["server", "full"] }
lazy-regex = "3.6"
mime_guess = "2.0"
polyfmt = { git = "https://github.com/clintjedwards/polyfmt-rs.git", tag = "v0.0.13" }
rand = "0.9"
regex = "1.13"
reqwest = { version = "0.12", features = [
    "json",
    "rustls-tls",
    "stream"
], default-features = false }
rstest = "0.27"
rust-embed = "8.12"
schemars = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite"] }
strum = { version = "0.28", features = ["derive"] }
tera = "1.20"
thiserror = "2.0"
tokio = { version = "1.53", features = ["full"] }
tokio-rustls = "0.26"
tokio-tungstenite = "0.26"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tungstenite = "0.26"
uuid = { version = "1.26", features = ["v7"] }
semver = "1.0"
libc = "0.2"
object_store = "0.12"
tokio-stream = "0.1"
http-body-util = "0.1"
tokio-util = "0.7"

[dev-dependencies]
figment = { version = "0.10", features = ["test"] }
lazy_static = "1.5"
tempfile = "3.27"
pretty_assertions = "1.4"

[[bin]]
name = "gofer"
path = "src/main.rs"

[[bin]]
name = "generate_openapi"
path = "src/generate_openapi.rs"
