#TODO(clintjedwards): comment all of this.
[general]
# dev_mode turns on humanized debug messages, extra debug logging for the webserver and other
# convenient features for development. Usually turned on along side log_level=debug.
dev_mode = true
log_level = "debug"
# Throughout Gofer we encrypt sensitive keys to keep them safe. This encryption key is reponsible
# for facilitating that. It MUST be 32 characters long and cannot be changed for any reason once
# it is set or else all data will be lost.
encryption_key = "changemechangemechangemechangeme"
# Events are only kept for a finite amount of time
event_prune_interval = 604800 # How often to clear out old events past the retention date (in seconds)
event_retention = 7889238     # At what age should events be pruned (in seconds)
run_parallelism_limit = 0     # The limit automatically imposed if the pipeline does not define a limit. 0 is unlimited

[server]
url = "127.0.0.1:8080"
storage_path = "/tmp/gofer.db"
tls_cert = ""
tls_key = ""

[scheduler]
engine = "Docker" # possible values: ["Docker"]

[scheduler.docker]
prune = true
prune_interval = 604800

[triggers]
# Certificate details used to connect from Gofer to the trigger containers.
# By default a generic trust store is used but you can add your own CA certificate to the trust store.
tls_cert = ""
tls_key = ""

[object_store]
engine = "Embedded" # possible values: ["Embedded"]

[object_store.embedded]
path = "/tmp/gofer-object-store"

[secert_store]
engine = "Embedded" # possible values: ["Embedded"]

[secert_store.embedded]
path = "/tmp/gofer-secret-store"
# Throughout Gofer we encrypt sensitive keys to keep them safe. This encryption key is reponsible
# for facilitating that. It MUST be 32 characters long and cannot be changed for any reason once
# it is set or else all data will be lost.
encryption_key = "changemechangemechangemechangeme"
