[book]
authors = ["Clint J Edwards"]
language = "en"
multilingual = false
src = "src"
title = "Gofer"
description = "Gofer documentation"

[output.html]

[output.linkcheck]
# Keep this until [this bug](https://github.com/rust-lang/mdBook/issues/984) gets fixed
exclude = [ 'index\.html' ]

